/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createImageToImageResponseFromDiscriminatorValue, serializeImageToImageResponse, serializeStableDiffusionProcessingImg2Img, type ImageToImageResponse, type StableDiffusionProcessingImg2Img } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /img2img
 */
export interface Img2imgRequestBuilder extends BaseRequestBuilder<Img2imgRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ImageToImageResponse>}
     */
     post(body: StableDiffusionProcessingImg2Img, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ImageToImageResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: StableDiffusionProcessingImg2Img, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Img2imgRequestBuilderUriTemplate = "{+baseurl}/img2img";
/**
 * Metadata for all the requests in the request builder.
 */
export const Img2imgRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Img2imgRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createImageToImageResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeStableDiffusionProcessingImg2Img,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
