/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ImageToImageResponse_additionalData}
 */
// @ts-ignore
export function createImageToImageResponse_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoImageToImageResponse_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ImageToImageResponse_parameters_additionalData}
 */
// @ts-ignore
export function createImageToImageResponse_parameters_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoImageToImageResponse_parameters_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ImageToImageResponse_parameters}
 */
// @ts-ignore
export function createImageToImageResponse_parametersFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoImageToImageResponse_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ImageToImageResponse}
 */
// @ts-ignore
export function createImageToImageResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoImageToImageResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_alwayson_scripts_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_alwayson_scripts_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_alwayson_scripts}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_alwayson_scriptsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_alwayson_scripts;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_comments_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_comments_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_comments_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_comments}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_commentsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_comments;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_override_settings_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_override_settings_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_override_settings_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img_override_settings}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2Img_override_settingsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img_override_settings;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingImg2Img}
 */
// @ts-ignore
export function createStableDiffusionProcessingImg2ImgFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingImg2Img;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_alwayson_scripts_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_alwayson_scripts}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_alwayson_scriptsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_alwayson_scripts;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_comments_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_comments_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_comments_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_comments}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_commentsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_comments;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_override_settings_additionalData}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_override_settings_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_override_settings_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img_override_settings}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2Img_override_settingsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img_override_settings;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StableDiffusionProcessingTxt2Img}
 */
// @ts-ignore
export function createStableDiffusionProcessingTxt2ImgFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStableDiffusionProcessingTxt2Img;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TextToImageResponse_additionalData}
 */
// @ts-ignore
export function createTextToImageResponse_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTextToImageResponse_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TextToImageResponse_parameters_additionalData}
 */
// @ts-ignore
export function createTextToImageResponse_parameters_additionalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTextToImageResponse_parameters_additionalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TextToImageResponse_parameters}
 */
// @ts-ignore
export function createTextToImageResponse_parametersFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTextToImageResponse_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TextToImageResponse}
 */
// @ts-ignore
export function createTextToImageResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTextToImageResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UntypedNode}
 */
// @ts-ignore
export function createUntypedNodeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUntypedNode;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoImageToImageResponse(imageToImageResponse: Partial<ImageToImageResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { imageToImageResponse.additionalDataProperty = n.getObjectValue<ImageToImageResponse_additionalData>(createImageToImageResponse_additionalDataFromDiscriminatorValue); },
        "images": n => { imageToImageResponse.images = n.getCollectionOfPrimitiveValues<string>(); },
        "info": n => { imageToImageResponse.info = n.getStringValue(); },
        "parameters": n => { imageToImageResponse.parameters = n.getObjectValue<ImageToImageResponse_parameters>(createImageToImageResponse_parametersFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoImageToImageResponse_additionalData(imageToImageResponse_additionalData: Partial<ImageToImageResponse_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoImageToImageResponse_parameters(imageToImageResponse_parameters: Partial<ImageToImageResponse_parameters> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { imageToImageResponse_parameters.additionalDataProperty = n.getObjectValue<ImageToImageResponse_parameters_additionalData>(createImageToImageResponse_parameters_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoImageToImageResponse_parameters_additionalData(imageToImageResponse_parameters_additionalData: Partial<ImageToImageResponse_parameters_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img(stableDiffusionProcessingImg2Img: Partial<StableDiffusionProcessingImg2Img> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingImg2Img.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingImg2Img_additionalData>(createStableDiffusionProcessingImg2Img_additionalDataFromDiscriminatorValue); },
        "alwaysonScripts": n => { stableDiffusionProcessingImg2Img.alwaysonScripts = n.getObjectValue<StableDiffusionProcessingImg2Img_alwayson_scripts>(createStableDiffusionProcessingImg2Img_alwayson_scriptsFromDiscriminatorValue); },
        "batchSize": n => { stableDiffusionProcessingImg2Img.batchSize = n.getNumberValue(); },
        "cfgScale": n => { stableDiffusionProcessingImg2Img.cfgScale = n.getNumberValue(); },
        "comments": n => { stableDiffusionProcessingImg2Img.comments = n.getObjectValue<StableDiffusionProcessingImg2Img_comments>(createStableDiffusionProcessingImg2Img_commentsFromDiscriminatorValue); },
        "denoisingStrength": n => { stableDiffusionProcessingImg2Img.denoisingStrength = n.getNumberValue(); },
        "disableExtraNetworks": n => { stableDiffusionProcessingImg2Img.disableExtraNetworks = n.getBooleanValue(); },
        "doNotSaveGrid": n => { stableDiffusionProcessingImg2Img.doNotSaveGrid = n.getBooleanValue(); },
        "doNotSaveSamples": n => { stableDiffusionProcessingImg2Img.doNotSaveSamples = n.getBooleanValue(); },
        "eta": n => { stableDiffusionProcessingImg2Img.eta = n.getNumberValue(); },
        "firstpassImage": n => { stableDiffusionProcessingImg2Img.firstpassImage = n.getStringValue(); },
        "forceTaskId": n => { stableDiffusionProcessingImg2Img.forceTaskId = n.getStringValue(); },
        "height": n => { stableDiffusionProcessingImg2Img.height = n.getNumberValue(); },
        "imageCfgScale": n => { stableDiffusionProcessingImg2Img.imageCfgScale = n.getNumberValue(); },
        "includeInitImages": n => { stableDiffusionProcessingImg2Img.includeInitImages = n.getBooleanValue(); },
        "infotext": n => { stableDiffusionProcessingImg2Img.infotext = n.getStringValue(); },
        "initialNoiseMultiplier": n => { stableDiffusionProcessingImg2Img.initialNoiseMultiplier = n.getNumberValue(); },
        "initImages": n => { stableDiffusionProcessingImg2Img.initImages = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "inpaintFullRes": n => { stableDiffusionProcessingImg2Img.inpaintFullRes = n.getBooleanValue(); },
        "inpaintFullResPadding": n => { stableDiffusionProcessingImg2Img.inpaintFullResPadding = n.getNumberValue(); },
        "inpaintingFill": n => { stableDiffusionProcessingImg2Img.inpaintingFill = n.getNumberValue(); },
        "inpaintingMaskInvert": n => { stableDiffusionProcessingImg2Img.inpaintingMaskInvert = n.getNumberValue(); },
        "latentMask": n => { stableDiffusionProcessingImg2Img.latentMask = n.getStringValue(); },
        "mask": n => { stableDiffusionProcessingImg2Img.mask = n.getStringValue(); },
        "maskBlur": n => { stableDiffusionProcessingImg2Img.maskBlur = n.getNumberValue(); },
        "maskBlurX": n => { stableDiffusionProcessingImg2Img.maskBlurX = n.getNumberValue(); },
        "maskBlurY": n => { stableDiffusionProcessingImg2Img.maskBlurY = n.getNumberValue(); },
        "maskRound": n => { stableDiffusionProcessingImg2Img.maskRound = n.getBooleanValue(); },
        "negativePrompt": n => { stableDiffusionProcessingImg2Img.negativePrompt = n.getStringValue(); },
        "nIter": n => { stableDiffusionProcessingImg2Img.nIter = n.getNumberValue(); },
        "overrideSettings": n => { stableDiffusionProcessingImg2Img.overrideSettings = n.getObjectValue<StableDiffusionProcessingImg2Img_override_settings>(createStableDiffusionProcessingImg2Img_override_settingsFromDiscriminatorValue); },
        "overrideSettingsRestoreAfterwards": n => { stableDiffusionProcessingImg2Img.overrideSettingsRestoreAfterwards = n.getBooleanValue(); },
        "prompt": n => { stableDiffusionProcessingImg2Img.prompt = n.getStringValue(); },
        "refinerCheckpoint": n => { stableDiffusionProcessingImg2Img.refinerCheckpoint = n.getStringValue(); },
        "refinerSwitchAt": n => { stableDiffusionProcessingImg2Img.refinerSwitchAt = n.getNumberValue(); },
        "resizeMode": n => { stableDiffusionProcessingImg2Img.resizeMode = n.getNumberValue(); },
        "restoreFaces": n => { stableDiffusionProcessingImg2Img.restoreFaces = n.getBooleanValue(); },
        "samplerIndex": n => { stableDiffusionProcessingImg2Img.samplerIndex = n.getStringValue(); },
        "samplerName": n => { stableDiffusionProcessingImg2Img.samplerName = n.getStringValue(); },
        "saveImages": n => { stableDiffusionProcessingImg2Img.saveImages = n.getBooleanValue(); },
        "scheduler": n => { stableDiffusionProcessingImg2Img.scheduler = n.getStringValue(); },
        "sChurn": n => { stableDiffusionProcessingImg2Img.sChurn = n.getNumberValue(); },
        "scriptArgs": n => { stableDiffusionProcessingImg2Img.scriptArgs = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "scriptName": n => { stableDiffusionProcessingImg2Img.scriptName = n.getStringValue(); },
        "seed": n => { stableDiffusionProcessingImg2Img.seed = n.getNumberValue(); },
        "seedResizeFromH": n => { stableDiffusionProcessingImg2Img.seedResizeFromH = n.getNumberValue(); },
        "seedResizeFromW": n => { stableDiffusionProcessingImg2Img.seedResizeFromW = n.getNumberValue(); },
        "sendImages": n => { stableDiffusionProcessingImg2Img.sendImages = n.getBooleanValue(); },
        "sMinUncond": n => { stableDiffusionProcessingImg2Img.sMinUncond = n.getNumberValue(); },
        "sNoise": n => { stableDiffusionProcessingImg2Img.sNoise = n.getNumberValue(); },
        "steps": n => { stableDiffusionProcessingImg2Img.steps = n.getNumberValue(); },
        "sTmax": n => { stableDiffusionProcessingImg2Img.sTmax = n.getNumberValue(); },
        "sTmin": n => { stableDiffusionProcessingImg2Img.sTmin = n.getNumberValue(); },
        "styles": n => { stableDiffusionProcessingImg2Img.styles = n.getCollectionOfPrimitiveValues<string>(); },
        "subseed": n => { stableDiffusionProcessingImg2Img.subseed = n.getNumberValue(); },
        "subseedStrength": n => { stableDiffusionProcessingImg2Img.subseedStrength = n.getNumberValue(); },
        "tiling": n => { stableDiffusionProcessingImg2Img.tiling = n.getBooleanValue(); },
        "width": n => { stableDiffusionProcessingImg2Img.width = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_additionalData(stableDiffusionProcessingImg2Img_additionalData: Partial<StableDiffusionProcessingImg2Img_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_alwayson_scripts(stableDiffusionProcessingImg2Img_alwayson_scripts: Partial<StableDiffusionProcessingImg2Img_alwayson_scripts> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingImg2Img_alwayson_scripts.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData>(createStableDiffusionProcessingImg2Img_alwayson_scripts_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_alwayson_scripts_additionalData(stableDiffusionProcessingImg2Img_alwayson_scripts_additionalData: Partial<StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_comments(stableDiffusionProcessingImg2Img_comments: Partial<StableDiffusionProcessingImg2Img_comments> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingImg2Img_comments.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingImg2Img_comments_additionalData>(createStableDiffusionProcessingImg2Img_comments_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_comments_additionalData(stableDiffusionProcessingImg2Img_comments_additionalData: Partial<StableDiffusionProcessingImg2Img_comments_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_override_settings(stableDiffusionProcessingImg2Img_override_settings: Partial<StableDiffusionProcessingImg2Img_override_settings> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingImg2Img_override_settings.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingImg2Img_override_settings_additionalData>(createStableDiffusionProcessingImg2Img_override_settings_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingImg2Img_override_settings_additionalData(stableDiffusionProcessingImg2Img_override_settings_additionalData: Partial<StableDiffusionProcessingImg2Img_override_settings_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img(stableDiffusionProcessingTxt2Img: Partial<StableDiffusionProcessingTxt2Img> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingTxt2Img.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingTxt2Img_additionalData>(createStableDiffusionProcessingTxt2Img_additionalDataFromDiscriminatorValue); },
        "alwaysonScripts": n => { stableDiffusionProcessingTxt2Img.alwaysonScripts = n.getObjectValue<StableDiffusionProcessingTxt2Img_alwayson_scripts>(createStableDiffusionProcessingTxt2Img_alwayson_scriptsFromDiscriminatorValue); },
        "batchSize": n => { stableDiffusionProcessingTxt2Img.batchSize = n.getNumberValue(); },
        "cfgScale": n => { stableDiffusionProcessingTxt2Img.cfgScale = n.getNumberValue(); },
        "comments": n => { stableDiffusionProcessingTxt2Img.comments = n.getObjectValue<StableDiffusionProcessingTxt2Img_comments>(createStableDiffusionProcessingTxt2Img_commentsFromDiscriminatorValue); },
        "denoisingStrength": n => { stableDiffusionProcessingTxt2Img.denoisingStrength = n.getNumberValue(); },
        "disableExtraNetworks": n => { stableDiffusionProcessingTxt2Img.disableExtraNetworks = n.getBooleanValue(); },
        "doNotSaveGrid": n => { stableDiffusionProcessingTxt2Img.doNotSaveGrid = n.getBooleanValue(); },
        "doNotSaveSamples": n => { stableDiffusionProcessingTxt2Img.doNotSaveSamples = n.getBooleanValue(); },
        "enableHr": n => { stableDiffusionProcessingTxt2Img.enableHr = n.getBooleanValue(); },
        "eta": n => { stableDiffusionProcessingTxt2Img.eta = n.getNumberValue(); },
        "firstpassImage": n => { stableDiffusionProcessingTxt2Img.firstpassImage = n.getStringValue(); },
        "firstphaseHeight": n => { stableDiffusionProcessingTxt2Img.firstphaseHeight = n.getNumberValue(); },
        "firstphaseWidth": n => { stableDiffusionProcessingTxt2Img.firstphaseWidth = n.getNumberValue(); },
        "forceTaskId": n => { stableDiffusionProcessingTxt2Img.forceTaskId = n.getStringValue(); },
        "height": n => { stableDiffusionProcessingTxt2Img.height = n.getNumberValue(); },
        "hrCheckpointName": n => { stableDiffusionProcessingTxt2Img.hrCheckpointName = n.getStringValue(); },
        "hrNegativePrompt": n => { stableDiffusionProcessingTxt2Img.hrNegativePrompt = n.getStringValue(); },
        "hrPrompt": n => { stableDiffusionProcessingTxt2Img.hrPrompt = n.getStringValue(); },
        "hrResizeX": n => { stableDiffusionProcessingTxt2Img.hrResizeX = n.getNumberValue(); },
        "hrResizeY": n => { stableDiffusionProcessingTxt2Img.hrResizeY = n.getNumberValue(); },
        "hrSamplerName": n => { stableDiffusionProcessingTxt2Img.hrSamplerName = n.getStringValue(); },
        "hrScale": n => { stableDiffusionProcessingTxt2Img.hrScale = n.getNumberValue(); },
        "hrScheduler": n => { stableDiffusionProcessingTxt2Img.hrScheduler = n.getStringValue(); },
        "hrSecondPassSteps": n => { stableDiffusionProcessingTxt2Img.hrSecondPassSteps = n.getNumberValue(); },
        "hrUpscaler": n => { stableDiffusionProcessingTxt2Img.hrUpscaler = n.getStringValue(); },
        "infotext": n => { stableDiffusionProcessingTxt2Img.infotext = n.getStringValue(); },
        "negativePrompt": n => { stableDiffusionProcessingTxt2Img.negativePrompt = n.getStringValue(); },
        "nIter": n => { stableDiffusionProcessingTxt2Img.nIter = n.getNumberValue(); },
        "overrideSettings": n => { stableDiffusionProcessingTxt2Img.overrideSettings = n.getObjectValue<StableDiffusionProcessingTxt2Img_override_settings>(createStableDiffusionProcessingTxt2Img_override_settingsFromDiscriminatorValue); },
        "overrideSettingsRestoreAfterwards": n => { stableDiffusionProcessingTxt2Img.overrideSettingsRestoreAfterwards = n.getBooleanValue(); },
        "prompt": n => { stableDiffusionProcessingTxt2Img.prompt = n.getStringValue(); },
        "refinerCheckpoint": n => { stableDiffusionProcessingTxt2Img.refinerCheckpoint = n.getStringValue(); },
        "refinerSwitchAt": n => { stableDiffusionProcessingTxt2Img.refinerSwitchAt = n.getNumberValue(); },
        "restoreFaces": n => { stableDiffusionProcessingTxt2Img.restoreFaces = n.getBooleanValue(); },
        "samplerIndex": n => { stableDiffusionProcessingTxt2Img.samplerIndex = n.getStringValue(); },
        "samplerName": n => { stableDiffusionProcessingTxt2Img.samplerName = n.getStringValue(); },
        "saveImages": n => { stableDiffusionProcessingTxt2Img.saveImages = n.getBooleanValue(); },
        "scheduler": n => { stableDiffusionProcessingTxt2Img.scheduler = n.getStringValue(); },
        "sChurn": n => { stableDiffusionProcessingTxt2Img.sChurn = n.getNumberValue(); },
        "scriptArgs": n => { stableDiffusionProcessingTxt2Img.scriptArgs = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "scriptName": n => { stableDiffusionProcessingTxt2Img.scriptName = n.getStringValue(); },
        "seed": n => { stableDiffusionProcessingTxt2Img.seed = n.getNumberValue(); },
        "seedResizeFromH": n => { stableDiffusionProcessingTxt2Img.seedResizeFromH = n.getNumberValue(); },
        "seedResizeFromW": n => { stableDiffusionProcessingTxt2Img.seedResizeFromW = n.getNumberValue(); },
        "sendImages": n => { stableDiffusionProcessingTxt2Img.sendImages = n.getBooleanValue(); },
        "sMinUncond": n => { stableDiffusionProcessingTxt2Img.sMinUncond = n.getNumberValue(); },
        "sNoise": n => { stableDiffusionProcessingTxt2Img.sNoise = n.getNumberValue(); },
        "steps": n => { stableDiffusionProcessingTxt2Img.steps = n.getNumberValue(); },
        "sTmax": n => { stableDiffusionProcessingTxt2Img.sTmax = n.getNumberValue(); },
        "sTmin": n => { stableDiffusionProcessingTxt2Img.sTmin = n.getNumberValue(); },
        "styles": n => { stableDiffusionProcessingTxt2Img.styles = n.getCollectionOfPrimitiveValues<string>(); },
        "subseed": n => { stableDiffusionProcessingTxt2Img.subseed = n.getNumberValue(); },
        "subseedStrength": n => { stableDiffusionProcessingTxt2Img.subseedStrength = n.getNumberValue(); },
        "tiling": n => { stableDiffusionProcessingTxt2Img.tiling = n.getBooleanValue(); },
        "width": n => { stableDiffusionProcessingTxt2Img.width = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_additionalData(stableDiffusionProcessingTxt2Img_additionalData: Partial<StableDiffusionProcessingTxt2Img_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_alwayson_scripts(stableDiffusionProcessingTxt2Img_alwayson_scripts: Partial<StableDiffusionProcessingTxt2Img_alwayson_scripts> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingTxt2Img_alwayson_scripts.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData>(createStableDiffusionProcessingTxt2Img_alwayson_scripts_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData(stableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData: Partial<StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_comments(stableDiffusionProcessingTxt2Img_comments: Partial<StableDiffusionProcessingTxt2Img_comments> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingTxt2Img_comments.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingTxt2Img_comments_additionalData>(createStableDiffusionProcessingTxt2Img_comments_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_comments_additionalData(stableDiffusionProcessingTxt2Img_comments_additionalData: Partial<StableDiffusionProcessingTxt2Img_comments_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_override_settings(stableDiffusionProcessingTxt2Img_override_settings: Partial<StableDiffusionProcessingTxt2Img_override_settings> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { stableDiffusionProcessingTxt2Img_override_settings.additionalDataProperty = n.getObjectValue<StableDiffusionProcessingTxt2Img_override_settings_additionalData>(createStableDiffusionProcessingTxt2Img_override_settings_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStableDiffusionProcessingTxt2Img_override_settings_additionalData(stableDiffusionProcessingTxt2Img_override_settings_additionalData: Partial<StableDiffusionProcessingTxt2Img_override_settings_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTextToImageResponse(textToImageResponse: Partial<TextToImageResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { textToImageResponse.additionalDataProperty = n.getObjectValue<TextToImageResponse_additionalData>(createTextToImageResponse_additionalDataFromDiscriminatorValue); },
        "images": n => { textToImageResponse.images = n.getCollectionOfPrimitiveValues<string>(); },
        "info": n => { textToImageResponse.info = n.getStringValue(); },
        "parameters": n => { textToImageResponse.parameters = n.getObjectValue<TextToImageResponse_parameters>(createTextToImageResponse_parametersFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTextToImageResponse_additionalData(textToImageResponse_additionalData: Partial<TextToImageResponse_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTextToImageResponse_parameters(textToImageResponse_parameters: Partial<TextToImageResponse_parameters> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "additionalData": n => { textToImageResponse_parameters.additionalDataProperty = n.getObjectValue<TextToImageResponse_parameters_additionalData>(createTextToImageResponse_parameters_additionalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTextToImageResponse_parameters_additionalData(textToImageResponse_parameters_additionalData: Partial<TextToImageResponse_parameters_additionalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUntypedNode(untypedNode: Partial<UntypedNode> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface ImageToImageResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: ImageToImageResponse_additionalData | null;
    /**
     * The images property
     */
    images?: string[] | null;
    /**
     * The info property
     */
    info?: string | null;
    /**
     * The parameters property
     */
    parameters?: ImageToImageResponse_parameters | null;
}
export interface ImageToImageResponse_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface ImageToImageResponse_parameters extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: ImageToImageResponse_parameters_additionalData | null;
}
export interface ImageToImageResponse_parameters_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeImageToImageResponse(writer: SerializationWriter, imageToImageResponse: Partial<ImageToImageResponse> | undefined | null = {}) : void {
    if (imageToImageResponse) {
        writer.writeObjectValue<ImageToImageResponse_additionalData>("additionalData", imageToImageResponse.additionalDataProperty, serializeImageToImageResponse_additionalData);
        writer.writeCollectionOfPrimitiveValues<string>("images", imageToImageResponse.images);
        writer.writeStringValue("info", imageToImageResponse.info);
        writer.writeObjectValue<ImageToImageResponse_parameters>("parameters", imageToImageResponse.parameters, serializeImageToImageResponse_parameters);
        writer.writeAdditionalData(imageToImageResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeImageToImageResponse_additionalData(writer: SerializationWriter, imageToImageResponse_additionalData: Partial<ImageToImageResponse_additionalData> | undefined | null = {}) : void {
    if (imageToImageResponse_additionalData) {
        writer.writeAdditionalData(imageToImageResponse_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeImageToImageResponse_parameters(writer: SerializationWriter, imageToImageResponse_parameters: Partial<ImageToImageResponse_parameters> | undefined | null = {}) : void {
    if (imageToImageResponse_parameters) {
        writer.writeObjectValue<ImageToImageResponse_parameters_additionalData>("additionalData", imageToImageResponse_parameters.additionalDataProperty, serializeImageToImageResponse_parameters_additionalData);
        writer.writeAdditionalData(imageToImageResponse_parameters.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeImageToImageResponse_parameters_additionalData(writer: SerializationWriter, imageToImageResponse_parameters_additionalData: Partial<ImageToImageResponse_parameters_additionalData> | undefined | null = {}) : void {
    if (imageToImageResponse_parameters_additionalData) {
        writer.writeAdditionalData(imageToImageResponse_parameters_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img(writer: SerializationWriter, stableDiffusionProcessingImg2Img: Partial<StableDiffusionProcessingImg2Img> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img) {
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_additionalData>("additionalData", stableDiffusionProcessingImg2Img.additionalDataProperty, serializeStableDiffusionProcessingImg2Img_additionalData);
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_alwayson_scripts>("alwaysonScripts", stableDiffusionProcessingImg2Img.alwaysonScripts, serializeStableDiffusionProcessingImg2Img_alwayson_scripts);
        writer.writeNumberValue("batchSize", stableDiffusionProcessingImg2Img.batchSize);
        writer.writeNumberValue("cfgScale", stableDiffusionProcessingImg2Img.cfgScale);
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_comments>("comments", stableDiffusionProcessingImg2Img.comments, serializeStableDiffusionProcessingImg2Img_comments);
        writer.writeNumberValue("denoisingStrength", stableDiffusionProcessingImg2Img.denoisingStrength);
        writer.writeBooleanValue("disableExtraNetworks", stableDiffusionProcessingImg2Img.disableExtraNetworks);
        writer.writeBooleanValue("doNotSaveGrid", stableDiffusionProcessingImg2Img.doNotSaveGrid);
        writer.writeBooleanValue("doNotSaveSamples", stableDiffusionProcessingImg2Img.doNotSaveSamples);
        writer.writeNumberValue("eta", stableDiffusionProcessingImg2Img.eta);
        writer.writeStringValue("firstpassImage", stableDiffusionProcessingImg2Img.firstpassImage);
        writer.writeStringValue("forceTaskId", stableDiffusionProcessingImg2Img.forceTaskId);
        writer.writeNumberValue("height", stableDiffusionProcessingImg2Img.height);
        writer.writeNumberValue("imageCfgScale", stableDiffusionProcessingImg2Img.imageCfgScale);
        writer.writeBooleanValue("includeInitImages", stableDiffusionProcessingImg2Img.includeInitImages);
        writer.writeStringValue("infotext", stableDiffusionProcessingImg2Img.infotext);
        writer.writeNumberValue("initialNoiseMultiplier", stableDiffusionProcessingImg2Img.initialNoiseMultiplier);
        writer.writeObjectValue<UntypedNode>("initImages", stableDiffusionProcessingImg2Img.initImages, serializeUntypedNode);
        writer.writeBooleanValue("inpaintFullRes", stableDiffusionProcessingImg2Img.inpaintFullRes);
        writer.writeNumberValue("inpaintFullResPadding", stableDiffusionProcessingImg2Img.inpaintFullResPadding);
        writer.writeNumberValue("inpaintingFill", stableDiffusionProcessingImg2Img.inpaintingFill);
        writer.writeNumberValue("inpaintingMaskInvert", stableDiffusionProcessingImg2Img.inpaintingMaskInvert);
        writer.writeStringValue("latentMask", stableDiffusionProcessingImg2Img.latentMask);
        writer.writeStringValue("mask", stableDiffusionProcessingImg2Img.mask);
        writer.writeNumberValue("maskBlur", stableDiffusionProcessingImg2Img.maskBlur);
        writer.writeNumberValue("maskBlurX", stableDiffusionProcessingImg2Img.maskBlurX);
        writer.writeNumberValue("maskBlurY", stableDiffusionProcessingImg2Img.maskBlurY);
        writer.writeBooleanValue("maskRound", stableDiffusionProcessingImg2Img.maskRound);
        writer.writeStringValue("negativePrompt", stableDiffusionProcessingImg2Img.negativePrompt);
        writer.writeNumberValue("nIter", stableDiffusionProcessingImg2Img.nIter);
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_override_settings>("overrideSettings", stableDiffusionProcessingImg2Img.overrideSettings, serializeStableDiffusionProcessingImg2Img_override_settings);
        writer.writeBooleanValue("overrideSettingsRestoreAfterwards", stableDiffusionProcessingImg2Img.overrideSettingsRestoreAfterwards);
        writer.writeStringValue("prompt", stableDiffusionProcessingImg2Img.prompt);
        writer.writeStringValue("refinerCheckpoint", stableDiffusionProcessingImg2Img.refinerCheckpoint);
        writer.writeNumberValue("refinerSwitchAt", stableDiffusionProcessingImg2Img.refinerSwitchAt);
        writer.writeNumberValue("resizeMode", stableDiffusionProcessingImg2Img.resizeMode);
        writer.writeBooleanValue("restoreFaces", stableDiffusionProcessingImg2Img.restoreFaces);
        writer.writeStringValue("samplerIndex", stableDiffusionProcessingImg2Img.samplerIndex);
        writer.writeStringValue("samplerName", stableDiffusionProcessingImg2Img.samplerName);
        writer.writeBooleanValue("saveImages", stableDiffusionProcessingImg2Img.saveImages);
        writer.writeStringValue("scheduler", stableDiffusionProcessingImg2Img.scheduler);
        writer.writeNumberValue("sChurn", stableDiffusionProcessingImg2Img.sChurn);
        writer.writeObjectValue<UntypedNode>("scriptArgs", stableDiffusionProcessingImg2Img.scriptArgs, serializeUntypedNode);
        writer.writeStringValue("scriptName", stableDiffusionProcessingImg2Img.scriptName);
        writer.writeNumberValue("seed", stableDiffusionProcessingImg2Img.seed);
        writer.writeNumberValue("seedResizeFromH", stableDiffusionProcessingImg2Img.seedResizeFromH);
        writer.writeNumberValue("seedResizeFromW", stableDiffusionProcessingImg2Img.seedResizeFromW);
        writer.writeBooleanValue("sendImages", stableDiffusionProcessingImg2Img.sendImages);
        writer.writeNumberValue("sMinUncond", stableDiffusionProcessingImg2Img.sMinUncond);
        writer.writeNumberValue("sNoise", stableDiffusionProcessingImg2Img.sNoise);
        writer.writeNumberValue("steps", stableDiffusionProcessingImg2Img.steps);
        writer.writeNumberValue("sTmax", stableDiffusionProcessingImg2Img.sTmax);
        writer.writeNumberValue("sTmin", stableDiffusionProcessingImg2Img.sTmin);
        writer.writeCollectionOfPrimitiveValues<string>("styles", stableDiffusionProcessingImg2Img.styles);
        writer.writeNumberValue("subseed", stableDiffusionProcessingImg2Img.subseed);
        writer.writeNumberValue("subseedStrength", stableDiffusionProcessingImg2Img.subseedStrength);
        writer.writeBooleanValue("tiling", stableDiffusionProcessingImg2Img.tiling);
        writer.writeNumberValue("width", stableDiffusionProcessingImg2Img.width);
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_additionalData(writer: SerializationWriter, stableDiffusionProcessingImg2Img_additionalData: Partial<StableDiffusionProcessingImg2Img_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_alwayson_scripts(writer: SerializationWriter, stableDiffusionProcessingImg2Img_alwayson_scripts: Partial<StableDiffusionProcessingImg2Img_alwayson_scripts> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_alwayson_scripts) {
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData>("additionalData", stableDiffusionProcessingImg2Img_alwayson_scripts.additionalDataProperty, serializeStableDiffusionProcessingImg2Img_alwayson_scripts_additionalData);
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_alwayson_scripts.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_alwayson_scripts_additionalData(writer: SerializationWriter, stableDiffusionProcessingImg2Img_alwayson_scripts_additionalData: Partial<StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_alwayson_scripts_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_alwayson_scripts_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_comments(writer: SerializationWriter, stableDiffusionProcessingImg2Img_comments: Partial<StableDiffusionProcessingImg2Img_comments> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_comments) {
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_comments_additionalData>("additionalData", stableDiffusionProcessingImg2Img_comments.additionalDataProperty, serializeStableDiffusionProcessingImg2Img_comments_additionalData);
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_comments.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_comments_additionalData(writer: SerializationWriter, stableDiffusionProcessingImg2Img_comments_additionalData: Partial<StableDiffusionProcessingImg2Img_comments_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_comments_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_comments_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_override_settings(writer: SerializationWriter, stableDiffusionProcessingImg2Img_override_settings: Partial<StableDiffusionProcessingImg2Img_override_settings> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_override_settings) {
        writer.writeObjectValue<StableDiffusionProcessingImg2Img_override_settings_additionalData>("additionalData", stableDiffusionProcessingImg2Img_override_settings.additionalDataProperty, serializeStableDiffusionProcessingImg2Img_override_settings_additionalData);
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_override_settings.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingImg2Img_override_settings_additionalData(writer: SerializationWriter, stableDiffusionProcessingImg2Img_override_settings_additionalData: Partial<StableDiffusionProcessingImg2Img_override_settings_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingImg2Img_override_settings_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingImg2Img_override_settings_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img(writer: SerializationWriter, stableDiffusionProcessingTxt2Img: Partial<StableDiffusionProcessingTxt2Img> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img) {
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_additionalData>("additionalData", stableDiffusionProcessingTxt2Img.additionalDataProperty, serializeStableDiffusionProcessingTxt2Img_additionalData);
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_alwayson_scripts>("alwaysonScripts", stableDiffusionProcessingTxt2Img.alwaysonScripts, serializeStableDiffusionProcessingTxt2Img_alwayson_scripts);
        writer.writeNumberValue("batchSize", stableDiffusionProcessingTxt2Img.batchSize);
        writer.writeNumberValue("cfgScale", stableDiffusionProcessingTxt2Img.cfgScale);
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_comments>("comments", stableDiffusionProcessingTxt2Img.comments, serializeStableDiffusionProcessingTxt2Img_comments);
        writer.writeNumberValue("denoisingStrength", stableDiffusionProcessingTxt2Img.denoisingStrength);
        writer.writeBooleanValue("disableExtraNetworks", stableDiffusionProcessingTxt2Img.disableExtraNetworks);
        writer.writeBooleanValue("doNotSaveGrid", stableDiffusionProcessingTxt2Img.doNotSaveGrid);
        writer.writeBooleanValue("doNotSaveSamples", stableDiffusionProcessingTxt2Img.doNotSaveSamples);
        writer.writeBooleanValue("enableHr", stableDiffusionProcessingTxt2Img.enableHr);
        writer.writeNumberValue("eta", stableDiffusionProcessingTxt2Img.eta);
        writer.writeStringValue("firstpassImage", stableDiffusionProcessingTxt2Img.firstpassImage);
        writer.writeNumberValue("firstphaseHeight", stableDiffusionProcessingTxt2Img.firstphaseHeight);
        writer.writeNumberValue("firstphaseWidth", stableDiffusionProcessingTxt2Img.firstphaseWidth);
        writer.writeStringValue("forceTaskId", stableDiffusionProcessingTxt2Img.forceTaskId);
        writer.writeNumberValue("height", stableDiffusionProcessingTxt2Img.height);
        writer.writeStringValue("hrCheckpointName", stableDiffusionProcessingTxt2Img.hrCheckpointName);
        writer.writeStringValue("hrNegativePrompt", stableDiffusionProcessingTxt2Img.hrNegativePrompt);
        writer.writeStringValue("hrPrompt", stableDiffusionProcessingTxt2Img.hrPrompt);
        writer.writeNumberValue("hrResizeX", stableDiffusionProcessingTxt2Img.hrResizeX);
        writer.writeNumberValue("hrResizeY", stableDiffusionProcessingTxt2Img.hrResizeY);
        writer.writeStringValue("hrSamplerName", stableDiffusionProcessingTxt2Img.hrSamplerName);
        writer.writeNumberValue("hrScale", stableDiffusionProcessingTxt2Img.hrScale);
        writer.writeStringValue("hrScheduler", stableDiffusionProcessingTxt2Img.hrScheduler);
        writer.writeNumberValue("hrSecondPassSteps", stableDiffusionProcessingTxt2Img.hrSecondPassSteps);
        writer.writeStringValue("hrUpscaler", stableDiffusionProcessingTxt2Img.hrUpscaler);
        writer.writeStringValue("infotext", stableDiffusionProcessingTxt2Img.infotext);
        writer.writeStringValue("negativePrompt", stableDiffusionProcessingTxt2Img.negativePrompt);
        writer.writeNumberValue("nIter", stableDiffusionProcessingTxt2Img.nIter);
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_override_settings>("overrideSettings", stableDiffusionProcessingTxt2Img.overrideSettings, serializeStableDiffusionProcessingTxt2Img_override_settings);
        writer.writeBooleanValue("overrideSettingsRestoreAfterwards", stableDiffusionProcessingTxt2Img.overrideSettingsRestoreAfterwards);
        writer.writeStringValue("prompt", stableDiffusionProcessingTxt2Img.prompt);
        writer.writeStringValue("refinerCheckpoint", stableDiffusionProcessingTxt2Img.refinerCheckpoint);
        writer.writeNumberValue("refinerSwitchAt", stableDiffusionProcessingTxt2Img.refinerSwitchAt);
        writer.writeBooleanValue("restoreFaces", stableDiffusionProcessingTxt2Img.restoreFaces);
        writer.writeStringValue("samplerIndex", stableDiffusionProcessingTxt2Img.samplerIndex);
        writer.writeStringValue("samplerName", stableDiffusionProcessingTxt2Img.samplerName);
        writer.writeBooleanValue("saveImages", stableDiffusionProcessingTxt2Img.saveImages);
        writer.writeStringValue("scheduler", stableDiffusionProcessingTxt2Img.scheduler);
        writer.writeNumberValue("sChurn", stableDiffusionProcessingTxt2Img.sChurn);
        writer.writeObjectValue<UntypedNode>("scriptArgs", stableDiffusionProcessingTxt2Img.scriptArgs, serializeUntypedNode);
        writer.writeStringValue("scriptName", stableDiffusionProcessingTxt2Img.scriptName);
        writer.writeNumberValue("seed", stableDiffusionProcessingTxt2Img.seed);
        writer.writeNumberValue("seedResizeFromH", stableDiffusionProcessingTxt2Img.seedResizeFromH);
        writer.writeNumberValue("seedResizeFromW", stableDiffusionProcessingTxt2Img.seedResizeFromW);
        writer.writeBooleanValue("sendImages", stableDiffusionProcessingTxt2Img.sendImages);
        writer.writeNumberValue("sMinUncond", stableDiffusionProcessingTxt2Img.sMinUncond);
        writer.writeNumberValue("sNoise", stableDiffusionProcessingTxt2Img.sNoise);
        writer.writeNumberValue("steps", stableDiffusionProcessingTxt2Img.steps);
        writer.writeNumberValue("sTmax", stableDiffusionProcessingTxt2Img.sTmax);
        writer.writeNumberValue("sTmin", stableDiffusionProcessingTxt2Img.sTmin);
        writer.writeCollectionOfPrimitiveValues<string>("styles", stableDiffusionProcessingTxt2Img.styles);
        writer.writeNumberValue("subseed", stableDiffusionProcessingTxt2Img.subseed);
        writer.writeNumberValue("subseedStrength", stableDiffusionProcessingTxt2Img.subseedStrength);
        writer.writeBooleanValue("tiling", stableDiffusionProcessingTxt2Img.tiling);
        writer.writeNumberValue("width", stableDiffusionProcessingTxt2Img.width);
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_additionalData(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_additionalData: Partial<StableDiffusionProcessingTxt2Img_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_alwayson_scripts(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_alwayson_scripts: Partial<StableDiffusionProcessingTxt2Img_alwayson_scripts> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_alwayson_scripts) {
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData>("additionalData", stableDiffusionProcessingTxt2Img_alwayson_scripts.additionalDataProperty, serializeStableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData);
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_alwayson_scripts.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData: Partial<StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_comments(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_comments: Partial<StableDiffusionProcessingTxt2Img_comments> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_comments) {
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_comments_additionalData>("additionalData", stableDiffusionProcessingTxt2Img_comments.additionalDataProperty, serializeStableDiffusionProcessingTxt2Img_comments_additionalData);
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_comments.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_comments_additionalData(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_comments_additionalData: Partial<StableDiffusionProcessingTxt2Img_comments_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_comments_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_comments_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_override_settings(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_override_settings: Partial<StableDiffusionProcessingTxt2Img_override_settings> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_override_settings) {
        writer.writeObjectValue<StableDiffusionProcessingTxt2Img_override_settings_additionalData>("additionalData", stableDiffusionProcessingTxt2Img_override_settings.additionalDataProperty, serializeStableDiffusionProcessingTxt2Img_override_settings_additionalData);
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_override_settings.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStableDiffusionProcessingTxt2Img_override_settings_additionalData(writer: SerializationWriter, stableDiffusionProcessingTxt2Img_override_settings_additionalData: Partial<StableDiffusionProcessingTxt2Img_override_settings_additionalData> | undefined | null = {}) : void {
    if (stableDiffusionProcessingTxt2Img_override_settings_additionalData) {
        writer.writeAdditionalData(stableDiffusionProcessingTxt2Img_override_settings_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTextToImageResponse(writer: SerializationWriter, textToImageResponse: Partial<TextToImageResponse> | undefined | null = {}) : void {
    if (textToImageResponse) {
        writer.writeObjectValue<TextToImageResponse_additionalData>("additionalData", textToImageResponse.additionalDataProperty, serializeTextToImageResponse_additionalData);
        writer.writeCollectionOfPrimitiveValues<string>("images", textToImageResponse.images);
        writer.writeStringValue("info", textToImageResponse.info);
        writer.writeObjectValue<TextToImageResponse_parameters>("parameters", textToImageResponse.parameters, serializeTextToImageResponse_parameters);
        writer.writeAdditionalData(textToImageResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTextToImageResponse_additionalData(writer: SerializationWriter, textToImageResponse_additionalData: Partial<TextToImageResponse_additionalData> | undefined | null = {}) : void {
    if (textToImageResponse_additionalData) {
        writer.writeAdditionalData(textToImageResponse_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTextToImageResponse_parameters(writer: SerializationWriter, textToImageResponse_parameters: Partial<TextToImageResponse_parameters> | undefined | null = {}) : void {
    if (textToImageResponse_parameters) {
        writer.writeObjectValue<TextToImageResponse_parameters_additionalData>("additionalData", textToImageResponse_parameters.additionalDataProperty, serializeTextToImageResponse_parameters_additionalData);
        writer.writeAdditionalData(textToImageResponse_parameters.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTextToImageResponse_parameters_additionalData(writer: SerializationWriter, textToImageResponse_parameters_additionalData: Partial<TextToImageResponse_parameters_additionalData> | undefined | null = {}) : void {
    if (textToImageResponse_parameters_additionalData) {
        writer.writeAdditionalData(textToImageResponse_parameters_additionalData.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUntypedNode(writer: SerializationWriter, untypedNode: Partial<UntypedNode> | undefined | null = {}) : void {
    if (untypedNode) {
        writer.writeAdditionalData(untypedNode.additionalData);
    }
}
export interface StableDiffusionProcessingImg2Img extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingImg2Img_additionalData | null;
    /**
     * The alwaysonScripts property
     */
    alwaysonScripts?: StableDiffusionProcessingImg2Img_alwayson_scripts | null;
    /**
     * The batchSize property
     */
    batchSize?: number | null;
    /**
     * The cfgScale property
     */
    cfgScale?: number | null;
    /**
     * The comments property
     */
    comments?: StableDiffusionProcessingImg2Img_comments | null;
    /**
     * The denoisingStrength property
     */
    denoisingStrength?: number | null;
    /**
     * The disableExtraNetworks property
     */
    disableExtraNetworks?: boolean | null;
    /**
     * The doNotSaveGrid property
     */
    doNotSaveGrid?: boolean | null;
    /**
     * The doNotSaveSamples property
     */
    doNotSaveSamples?: boolean | null;
    /**
     * The eta property
     */
    eta?: number | null;
    /**
     * The firstpassImage property
     */
    firstpassImage?: string | null;
    /**
     * The forceTaskId property
     */
    forceTaskId?: string | null;
    /**
     * The height property
     */
    height?: number | null;
    /**
     * The imageCfgScale property
     */
    imageCfgScale?: number | null;
    /**
     * The includeInitImages property
     */
    includeInitImages?: boolean | null;
    /**
     * The infotext property
     */
    infotext?: string | null;
    /**
     * The initialNoiseMultiplier property
     */
    initialNoiseMultiplier?: number | null;
    /**
     * The initImages property
     */
    initImages?: UntypedNode | null;
    /**
     * The inpaintFullRes property
     */
    inpaintFullRes?: boolean | null;
    /**
     * The inpaintFullResPadding property
     */
    inpaintFullResPadding?: number | null;
    /**
     * The inpaintingFill property
     */
    inpaintingFill?: number | null;
    /**
     * The inpaintingMaskInvert property
     */
    inpaintingMaskInvert?: number | null;
    /**
     * The latentMask property
     */
    latentMask?: string | null;
    /**
     * The mask property
     */
    mask?: string | null;
    /**
     * The maskBlur property
     */
    maskBlur?: number | null;
    /**
     * The maskBlurX property
     */
    maskBlurX?: number | null;
    /**
     * The maskBlurY property
     */
    maskBlurY?: number | null;
    /**
     * The maskRound property
     */
    maskRound?: boolean | null;
    /**
     * The negativePrompt property
     */
    negativePrompt?: string | null;
    /**
     * The nIter property
     */
    nIter?: number | null;
    /**
     * The overrideSettings property
     */
    overrideSettings?: StableDiffusionProcessingImg2Img_override_settings | null;
    /**
     * The overrideSettingsRestoreAfterwards property
     */
    overrideSettingsRestoreAfterwards?: boolean | null;
    /**
     * The prompt property
     */
    prompt?: string | null;
    /**
     * The refinerCheckpoint property
     */
    refinerCheckpoint?: string | null;
    /**
     * The refinerSwitchAt property
     */
    refinerSwitchAt?: number | null;
    /**
     * The resizeMode property
     */
    resizeMode?: number | null;
    /**
     * The restoreFaces property
     */
    restoreFaces?: boolean | null;
    /**
     * The samplerIndex property
     */
    samplerIndex?: string | null;
    /**
     * The samplerName property
     */
    samplerName?: string | null;
    /**
     * The saveImages property
     */
    saveImages?: boolean | null;
    /**
     * The scheduler property
     */
    scheduler?: string | null;
    /**
     * The sChurn property
     */
    sChurn?: number | null;
    /**
     * The scriptArgs property
     */
    scriptArgs?: UntypedNode | null;
    /**
     * The scriptName property
     */
    scriptName?: string | null;
    /**
     * The seed property
     */
    seed?: number | null;
    /**
     * The seedResizeFromH property
     */
    seedResizeFromH?: number | null;
    /**
     * The seedResizeFromW property
     */
    seedResizeFromW?: number | null;
    /**
     * The sendImages property
     */
    sendImages?: boolean | null;
    /**
     * The sMinUncond property
     */
    sMinUncond?: number | null;
    /**
     * The sNoise property
     */
    sNoise?: number | null;
    /**
     * The steps property
     */
    steps?: number | null;
    /**
     * The sTmax property
     */
    sTmax?: number | null;
    /**
     * The sTmin property
     */
    sTmin?: number | null;
    /**
     * The styles property
     */
    styles?: string[] | null;
    /**
     * The subseed property
     */
    subseed?: number | null;
    /**
     * The subseedStrength property
     */
    subseedStrength?: number | null;
    /**
     * The tiling property
     */
    tiling?: boolean | null;
    /**
     * The width property
     */
    width?: number | null;
}
export interface StableDiffusionProcessingImg2Img_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingImg2Img_alwayson_scripts extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData | null;
}
export interface StableDiffusionProcessingImg2Img_alwayson_scripts_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingImg2Img_comments extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingImg2Img_comments_additionalData | null;
}
export interface StableDiffusionProcessingImg2Img_comments_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingImg2Img_override_settings extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingImg2Img_override_settings_additionalData | null;
}
export interface StableDiffusionProcessingImg2Img_override_settings_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingTxt2Img extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingTxt2Img_additionalData | null;
    /**
     * The alwaysonScripts property
     */
    alwaysonScripts?: StableDiffusionProcessingTxt2Img_alwayson_scripts | null;
    /**
     * The batchSize property
     */
    batchSize?: number | null;
    /**
     * The cfgScale property
     */
    cfgScale?: number | null;
    /**
     * The comments property
     */
    comments?: StableDiffusionProcessingTxt2Img_comments | null;
    /**
     * The denoisingStrength property
     */
    denoisingStrength?: number | null;
    /**
     * The disableExtraNetworks property
     */
    disableExtraNetworks?: boolean | null;
    /**
     * The doNotSaveGrid property
     */
    doNotSaveGrid?: boolean | null;
    /**
     * The doNotSaveSamples property
     */
    doNotSaveSamples?: boolean | null;
    /**
     * The enableHr property
     */
    enableHr?: boolean | null;
    /**
     * The eta property
     */
    eta?: number | null;
    /**
     * The firstpassImage property
     */
    firstpassImage?: string | null;
    /**
     * The firstphaseHeight property
     */
    firstphaseHeight?: number | null;
    /**
     * The firstphaseWidth property
     */
    firstphaseWidth?: number | null;
    /**
     * The forceTaskId property
     */
    forceTaskId?: string | null;
    /**
     * The height property
     */
    height?: number | null;
    /**
     * The hrCheckpointName property
     */
    hrCheckpointName?: string | null;
    /**
     * The hrNegativePrompt property
     */
    hrNegativePrompt?: string | null;
    /**
     * The hrPrompt property
     */
    hrPrompt?: string | null;
    /**
     * The hrResizeX property
     */
    hrResizeX?: number | null;
    /**
     * The hrResizeY property
     */
    hrResizeY?: number | null;
    /**
     * The hrSamplerName property
     */
    hrSamplerName?: string | null;
    /**
     * The hrScale property
     */
    hrScale?: number | null;
    /**
     * The hrScheduler property
     */
    hrScheduler?: string | null;
    /**
     * The hrSecondPassSteps property
     */
    hrSecondPassSteps?: number | null;
    /**
     * The hrUpscaler property
     */
    hrUpscaler?: string | null;
    /**
     * The infotext property
     */
    infotext?: string | null;
    /**
     * The negativePrompt property
     */
    negativePrompt?: string | null;
    /**
     * The nIter property
     */
    nIter?: number | null;
    /**
     * The overrideSettings property
     */
    overrideSettings?: StableDiffusionProcessingTxt2Img_override_settings | null;
    /**
     * The overrideSettingsRestoreAfterwards property
     */
    overrideSettingsRestoreAfterwards?: boolean | null;
    /**
     * The prompt property
     */
    prompt?: string | null;
    /**
     * The refinerCheckpoint property
     */
    refinerCheckpoint?: string | null;
    /**
     * The refinerSwitchAt property
     */
    refinerSwitchAt?: number | null;
    /**
     * The restoreFaces property
     */
    restoreFaces?: boolean | null;
    /**
     * The samplerIndex property
     */
    samplerIndex?: string | null;
    /**
     * The samplerName property
     */
    samplerName?: string | null;
    /**
     * The saveImages property
     */
    saveImages?: boolean | null;
    /**
     * The scheduler property
     */
    scheduler?: string | null;
    /**
     * The sChurn property
     */
    sChurn?: number | null;
    /**
     * The scriptArgs property
     */
    scriptArgs?: UntypedNode | null;
    /**
     * The scriptName property
     */
    scriptName?: string | null;
    /**
     * The seed property
     */
    seed?: number | null;
    /**
     * The seedResizeFromH property
     */
    seedResizeFromH?: number | null;
    /**
     * The seedResizeFromW property
     */
    seedResizeFromW?: number | null;
    /**
     * The sendImages property
     */
    sendImages?: boolean | null;
    /**
     * The sMinUncond property
     */
    sMinUncond?: number | null;
    /**
     * The sNoise property
     */
    sNoise?: number | null;
    /**
     * The steps property
     */
    steps?: number | null;
    /**
     * The sTmax property
     */
    sTmax?: number | null;
    /**
     * The sTmin property
     */
    sTmin?: number | null;
    /**
     * The styles property
     */
    styles?: string[] | null;
    /**
     * The subseed property
     */
    subseed?: number | null;
    /**
     * The subseedStrength property
     */
    subseedStrength?: number | null;
    /**
     * The tiling property
     */
    tiling?: boolean | null;
    /**
     * The width property
     */
    width?: number | null;
}
export interface StableDiffusionProcessingTxt2Img_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingTxt2Img_alwayson_scripts extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData | null;
}
export interface StableDiffusionProcessingTxt2Img_alwayson_scripts_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingTxt2Img_comments extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingTxt2Img_comments_additionalData | null;
}
export interface StableDiffusionProcessingTxt2Img_comments_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface StableDiffusionProcessingTxt2Img_override_settings extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: StableDiffusionProcessingTxt2Img_override_settings_additionalData | null;
}
export interface StableDiffusionProcessingTxt2Img_override_settings_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface TextToImageResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: TextToImageResponse_additionalData | null;
    /**
     * The images property
     */
    images?: string[] | null;
    /**
     * The info property
     */
    info?: string | null;
    /**
     * The parameters property
     */
    parameters?: TextToImageResponse_parameters | null;
}
export interface TextToImageResponse_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface TextToImageResponse_parameters extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The additionalDataProperty property
     */
    additionalDataProperty?: TextToImageResponse_parameters_additionalData | null;
}
export interface TextToImageResponse_parameters_additionalData extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface UntypedNode extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
/* tslint:enable */
/* eslint-enable */
